### ISSUE TITLE
`Scientific_workflows` should not be synced to the DEA Sandbox

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/dea-sandbox#100]
The `Scientific_workflows` folder appears to be being synced on the Sandbox:

![image](https://user-images.githubusercontent.com/17680388/89001198-d861ad80-d33c-11ea-8a40-024022b78f8b.png)

This folder was originally excluded from the folders that were synced to the Sandbox, as it contains larger scripts/sample data that won't work without additional set up. This causes issues if e.g. if a new user naively tries to use any of that code inside the Sandbox, as none of the code will work. This will lead to a poor user experience. 

To avoid this, this folder should be excluded from the automatic sync. 
(this was originally the case after the DEA Notebooks refresh earlier this year, but it seems to have reverted at some point)

**Comment by alexgleith** [comment]
This is where the folder needs to be added: https://github.com/GeoscienceAustralia/dea-sandbox/blob/develop/docker/assets/sync_repo

It's not a nice process though... pretty convoluted. Potentially needs cleaning up, @whatnick. Thoughts?

**Comment by robbibt** [comment]
Ah, OK! Does that one script work for both `DEAfrica` and `DEA Sandbox`? We should probably be excluding `DEA_notebooks_template.ipynb` too, not just the equivalent in Africa
