### ISSUE TITLE
'Give Feedback' bubble can't be moved and sits over code

### ISSUE THREAD

**Issue by BexDunn** [GeoscienceAustralia/dea-sandbox#101]
Can we please have a movable 'give feedback' bubble? It's super handy but when working in the terminal in the sandbox makes it a bit tricky to read some things. Being able to click on it and getting it to jump to top-right of screen or something similar would be great. Love the new option BTW, but mostly noticed it as it was over my terminal. Thanks

**Comment by benjimin** [comment]
Second that. Sure, it's nice to be able to figure out which repo to report issues to. But not so nice when you try to do other work, if it stays hovering over the top of the main editor pane forevermore. Maybe replace with a splash screen that can be dismissed (but that can also contain further introductory content)? Or at least move it to another pane, e.g. make it a tab on the navigation pane?

**Comment by pindge** [comment]
Improvement PR merged, the change will be applied when your pod is restarted.

On page load, the button will shrink to the side this animation is to give the user (especially first time user) an idea there is something. It will expand when the mouse hovers over it for 2seconds, and on mouse out, it will shrink in 1 or 2 seconds. It is not super smooth but it will shrink.

I will soon mark this issue closed.

**Comment by BexDunn** [comment]
Thanks @pindge , much better!
