### ISSUE TITLE
'Sign up' workflow allows multiple usernames to one email address

### ISSUE THREAD

**Issue by eefaye** [GeoscienceAustralia/dea-sandbox#103]
A user can sign up multiple usernames to the same email address. The sandbox only notifies the user this is invalid (only the first-registered username is usable) when the verification code has been entered, at which point the username is already claimed.

A possible solution would be to check the entered email address for an existing account on the 'Sign Up' page itself and prevent users from progressing if a duplicate is found.

Tested on the DE Africa Sandbox.

**Comment by pindge** [comment]
Closing this issue as it is not a system fault, it can be dealt with via support ticket.
