### ISSUE TITLE
Add vulnerability scanner as Cron task

### ISSUE THREAD

**Issue by whatnick** [GeoscienceAustralia/dea-sandbox#111]
https://github.com/GeoscienceAustralia/dea-sandbox/commit/a1068ecabe790cff118a4fe84b861c41fa0bed12#diff-f606a50abc4d0674f87194646274af3f removed in main CI pipeline vulnerability scanner. Add back as scheduled task.

**Comment by alexgleith** [comment]
Hey @Kirill888 can you please remind me why the vulnerability scanner was removed from CI?

**Comment by whatnick** [comment]
> Hey @Kirill888 can you please remind me why the vulnerability scanner was removed from CI?

I believe the CVE signature server is flaky ( since it is free) and sometimes times out. We can keep it and mark this step as continue on failure. There seems to be want for something like that as a feature in GHA : https://github.community/t/continue-on-error-allow-failure-ui-indication/16773
