### ISSUE TITLE
Fix CI to work with branch names with "/"

### ISSUE THREAD

**Issue by whatnick** [GeoscienceAustralia/dea-sandbox#117]
**Describe the bug**
CI uses dockerhub to cache build stages and this interacts poorly with branchnames

**To Reproduce**
Use a branchname with slashes.

**Expected behavior**
CI works irrespective of branch naming.

**Screenshots**
![image](https://user-images.githubusercontent.com/491396/91531417-1eb42780-e950-11ea-978e-bf7d344abbfa.png)

**Comment by Kirill888** [comment]
fixed
