### ISSUE TITLE
Domain access request from sandbox for GSKY WMS

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/dea-sandbox#119]
**What domain(s) needed? Please describe.**
https://gsky.nci.org.au/ows/dea

(may be better to add all of `*nci.org.au*`)

**Why this domain(s) needed? Please describe.**
To provide DEA visualisation imagery within a DEA Coastlines demonstration notebook

**Provide impacted notebook reference and purpose.**
Unpublished notebook being prepared for DEA Coastlines release

**Comment by NikitaGandhi** [comment]
can we close this @robbibt ?

**Comment by robbibt** [comment]
Yes, thankyou!
