### ISSUE TITLE
`python-geohash` library

### ISSUE THREAD

**Issue by MatthewJA** [GeoscienceAustralia/dea-sandbox#130]
**Is your feature request related to a problem? Please describe.**
`python-geohash` is required for producing DEA Waterbodies as geohashes are used for IDs.

**Describe the solution you'd like**
Could `python-geohash` please be installed on Sandbox?

**Describe alternatives you've considered**
We could `pip install python-geohash` locally, which is also fine, but it'd be nice if Waterbodies could easily be run without this.

**Comment by whatnick** [comment]
Consider using this instead : https://pypi.org/project/geohash2/

**Comment by Kirill888** [comment]
both `python-geohash` and `geohash2` are now available in "unstable".
