### ISSUE TITLE
Domain access request from sandbox - geoserver

### ISSUE THREAD

**Issue by MatthewJA** [GeoscienceAustralia/dea-sandbox#131]
**What domain(s) needed? Please describe.**
https://geoserver.dea.ga.gov.au/geoserver/wfs

Thanks :)

**Comment by vnewey** [comment]
I am able to access DEA waterbodies wfs  (https://geoserver.dea.ga.gov.au/geoserver/wfs) from VDI and Sandbox but not the Dev Sandbox. 
I am able to get some information back from this server. However if I query data, then I get a max tries exceeded and a timeout error.
Just reiterating I am asking for a change to the dev sandbox.  It already works on the sandbox.
It is not urgent.

**Comment by NikitaGandhi** [comment]
Updated the access. Please validate again.

**Comment by NikitaGandhi** [comment]
@MatthewJA can we close this ticket?

**Comment by MatthewJA** [comment]
@vnewey
