### ISSUE TITLE
Update Sandbox sync to use DEA-notebooks "stable" branch (not "master")

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/dea-sandbox#134]
We have just renamed the `master` branch of DEA notebooks to `stable` to better describe how we use it in contrast to `develop`:
https://github.com/GeoscienceAustralia/dea-notebooks/issues/589

This means the DEA Notebooks cloning to the Sandbox needs to be updated. Would it be possible to get this change made:

- Make the DEA Sandbox git clone from the DEA Notebooks `stable` branch (not `master`)

Branch in question here: https://github.com/GeoscienceAustralia/dea-notebooks/tree/stable

**Comment by Kirill888** [comment]
pretty sure Tisham fixed that
