### ISSUE TITLE
Update 'default/stable' sandbox

### ISSUE THREAD

**Issue by cbur24** [GeoscienceAustralia/dea-sandbox#137]
**Is your feature request related to a problem? Please describe.**
The default/stable sandbox has not been updated in some time, resulting in significant divergence between the unstable and stable images.  The divergence is starting to prevent merging of PRs to the master repo due to dependencies not being available on the default sandbox.  e.g. a lack of `rioxarray` and `dask-ml` is currently preventing merging of two PRs on the notebook-repo

**Describe the solution you'd like**
A new package release for the default sandbox

**Comment by Kirill888** [comment]
updated
