### ISSUE TITLE
DEA Sandbox missing autoformatter options that are part of DEA Notebooks quality control

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/dea-sandbox#139]
**Describe the bug**
The DEA Sandbox previously included the `jupyterlab_code_formatter` (https://jupyterlab-code-formatter.readthedocs.io/en/latest/) which allowed users to auto-format their code by clicking "Edit" then selecting "Apply PEP8", "Apply YAPF", or "Apply Black".

Since the recent DEA Sandbox update, these options are now missing from the "Edit" menu:

![image](https://user-images.githubusercontent.com/17680388/98308620-9b344800-201c-11eb-8171-98477e3d937f.png)

**To Reproduce**
Launch a DEA Sandbox kernel, click "Edit". The formatting options are missing from this menu.

**Expected behavior**
Users have access to these formatting options via the edit menu. These formatting options are an important part of the DEA Notebooks quality control process. Running them is a manditory step in the checklist required for publishing notebooks, e.g.:

> Use the PEP8 standard for code. To make sure all code in the notebook is consistent, you can use the jupyterlab_code_formatter tool: select each code cell, then click Edit and then one of the Apply X Formatter options (YAPF or Black are recommended). This will reformat the code in the cell to a consistent style.

> Ensure that all code cells follow the PEP8 standard for code. The jupyterlab_code_formatter tool can be used to format code cells to a consistent style: select each code cell, then click Edit and then one of the Apply X Formatter options (YAPF or Black are recommended).

https://github.com/GeoscienceAustralia/dea-notebooks/blob/develop/.github/PULL_REQUEST_TEMPLATE.md#checklist-replace---with-x-to-check-off

**Comment by Kirill888** [comment]
tyring to fix and fixed is different thing and github should be smarter about that

**Comment by Kirill888** [comment]
fixed in unstable, upgraded code formatter and jupyterlab and downgraded nbconvert as it was causing warnings on CLI, not sure which thing fixed it...
