### ISSUE TITLE
Data - Add the `srtm_dem1sv1_0` product

### ISSUE THREAD

**Issue by caitlinadams** [GeoscienceAustralia/dea-sandbox#14]
Requester: Robbi Bishop-Taylor

**Comment by alexgleith** [comment]
Is the SRTM data available somewhere?

We can't publish the DSM that is accessible on the NCI. I don't know about a DEM that we can share, do you know where it is @robbibt?

**Comment by robbibt** [comment]
Yep, just saw that the 1 second DSM is `This data is restricted for GOVERNMENT USE ONLY.`. I'll have a look for an alternative

**Comment by tom-butler** [comment]
As we can't add this specific dataset I'll close this issue for now, If you'd like us to add a different SRTM let us know in a separate issue.
