### ISSUE TITLE
Tools - Add digitalearthau

### ISSUE THREAD

**Issue by caitlinadams** [GeoscienceAustralia/dea-sandbox#15]
Requester: Bex Dunn
Flagged as high-priority by Robbi Bishop-Taylor and Bex Dunn.
In particular, the `wofs_fuser` function is important for several notebooks.

UPDATE: a copy of the `wofs_fuser` function has been moved to `dea-notebooks` repo, so `digitalearthau` module is no longer needed.

**Comment by robbibt** [comment]
No longer required due to copying the required `wofs_fuser` func to `dea_datahandling` in DEA Notebooks: https://github.com/GeoscienceAustralia/dea-notebooks/pull/403
