### ISSUE TITLE
Domain access request from sandbox: psl.noaa.gov

### ISSUE THREAD

**Issue by MatthewJA** [GeoscienceAustralia/dea-sandbox#155]
**What domain(s) needed? Please describe.**
psl.noaa.gov

**Why this domain(s) needed? Please describe.**
Access to climate data for DEA Waterbodies

**Comment by NikitaGandhi** [comment]
Requested domain got added to our list. @MatthewJA Please confirm.

**Comment by MatthewJA** [comment]
Works! Thank you!
