### ISSUE TITLE
Change base docker and Python version

### ISSUE THREAD

**Issue by Kirill888** [GeoscienceAustralia/dea-sandbox#173]
Current sandbox image is based on Python 3.6 and Ubuntu 18.04. This is starting to become problematic as libraries are starting to drop support for Python 3.6. In particular most recent versions of Dask and xarray no longer support it. It is becoming harder and harder to find a working set of libraries. Right now I needed to upgrade pyyaml due to serious CVE, that required upgrading boto libs to work with newer YAML, that in turn pulled in new urllib3 which is now incompatible with that last version pysal that supports 3.6. Problems like this will only get worse as time progresses, we won't be able to address serious security concerns if keep using current base image.

`geobase-{builder|runner}:3.3.0` is based on Ubuntu 20.04 and Python 3.8, and it works fine for running datacube-core and odc-tools tests.

Major issue would be dropping `rsgislib` this was manually done ages ago and only for Python 3.6, it's a conda only library that was packaged up in a dodgy way a while back and never since updated.

**Comment by robbibt** [comment]
Is this fixed on 2.0.0 @emmaai?
