### ISSUE TITLE
Simplify dea-sandbox image build

### ISSUE THREAD

**Issue by NikitaGandhi** [GeoscienceAustralia/dea-sandbox#183]
**Is your feature request related to a problem? Please describe.**
From Kirill:
Honestly I think the current approach is kinda broken. geobase images are useful for deployment of " focused tools", that only need datacube and maybe odc-tools in them. For a complex system like sandbox the size advantage you get by using builder/runner split is negligible.

**Describe the solution you'd like**

- simplify docker build by switching to a single stage docker image, like https://github.com/opendatacube/geobase/tree/develop/odc/odc-dev 

- Also consider options building one single conda environment deployable to both NCI and sandbox, just need to use nci compatible paths when baking that into sandbox docker.

**Describe alternatives you've considered**

**Additional context**

**Comment by omad** [comment]
I'm all for sharing the same environment between Sandbox and NCI, and a single `conda` environment is probably a good solution.

There is better tooling available now, including [conda-pack](https://conda.github.io/conda-pack/) which can relocate conda environment to different directories/machines, and [mamba](https://github.com/mamba-org/mamba) which is a rewritten `conda` tool which is orders of magnitude faster at resolving dependency trees.
