### ISSUE TITLE
Remove "Scientific_workflows" from DEA Sandbox sync

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/dea-sandbox#195]
**Is your feature request related to a problem? Please describe.**
Currently the "Scientific_workflows" folder of DEA Notebooks is automatically synced to the DEA Sandbox. This was never intended to be the case, as this folder contains experimental/unfinished/un-reviewed content that is not guaranteed to work correctly. This can cause confusion when new users try to run content in that directory, and incorrectly assume that it did not work due to something they did wrong.

**Describe the solution you'd like**
We should update the syncing script so that the "Scientific_workflows" folder is excluded from the folders that automatically appear at the top of the DEA Sandbox when users log in.

**Describe alternatives you've considered**
In the long run, we will likely remove this folder from DEA Notebooks altogether, however some projects (e.g. WIT) still rely on this folder for development.

**Comment by robbibt** [comment]
Hi @mmochan, this isn't urgent, but could I get your help implementing this change at some point? I know where the syncing code lives, but at the moment the only things excluded from the sync are files - I'm not sure of the best way to exclude an entire folder instead

**Comment by mmochan** [comment]
Hi @robbibt, sure no problem how about tomorrow morning?
