### ISSUE TITLE
Upgrade Geopandas to latest version `0.10.0`

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/dea-sandbox#202]
**Is your feature request related to a problem? Please describe.**
GeoPandas was recently updated to version 0.10.0 which has a number of important improvements that would simplify analysis of spatial vector data: https://github.com/geopandas/geopandas/releases/tag/v0.10.0

**Describe the solution you'd like**
Update `geopandas` on the DEA Sandbox to version 0.10.0 so that we can implement this updates in our code.

**Comment by NikitaGandhi** [comment]
@robbibt geopanda is already upgraded to `0.10.0` - https://github.com/GeoscienceAustralia/dea-sandbox/blob/develop/docker/constraints.txt#L88. Please make sure you are using `1.0.2` `dea-sandbox` image.

```
jovyan@jupyter-ngandhi:~$ pip list | grep geopandas
geopandas                         0.10.0
```

**Comment by robbibt** [comment]
Thanks @NikitaGandhi! That's really exciting, I'll close this issue
