### ISSUE TITLE
Improve DEA Sandbox tab name

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/dea-sandbox#247]
Currently, the DEA Sandbox JupyterLab uses the name "lab" as the tab name visible in a browser like Chrome:
![image](https://user-images.githubusercontent.com/17680388/219982119-64526c49-6f09-47bf-b9c7-4a1b922c7a3f.png)

It would be better to change the generic "lab" name to something like "DEA Sandbox" as this makes it more obvious what this specific instance of JupyterLab refers to.

This seems to provide instructions on how to achieve this:
https://github.com/jupyterlab/jupyterlab/issues/4422

**Comment by robbibt** [comment]
Not sure who the right person to tag with this is - @emmaai @treefern @stacyhorton?

**Comment by treefern** [comment]
> This seems to provide instructions on how to achieve this: [jupyterlab/jupyterlab#4422](https://github.com/jupyterlab/jupyterlab/issues/4422)

Bouncing through the historic linked PRs, it initially looks like a solution was implemented years ago... then appears not... then there's this, which looks like the solution:
https://github.com/GeoscienceAustralia/dea-sandbox/pull/68/commits/5db15d825174d1b832c7ad395c09d0458f2d5d62

**Comment by robbibt** [comment]
I think Pin has sorted this one already - plus a favicon!
![image](https://user-images.githubusercontent.com/17680388/220484757-584078ca-ce8c-4cbd-adea-a6482a0c4e4b.png)

**Comment by robbibt** [comment]
I think this is fixed now - thanks @pindge !
