### ISSUE TITLE
Sandbox - Update `datacube-core` to be greater than version 1.7

### ISSUE THREAD

**Issue by caitlinadams** [GeoscienceAustralia/dea-sandbox#26]
Requester: Robbi Bishop-Taylor
Flagged as high-priority by Robbi Bishop-Taylor

Necessary to use the virtual products feature. For example, see https://nbviewer.jupyter.org/github/GeoscienceAustralia/dea-notebooks/blob/cdec7173c06bcb800638c047ecfde8034b02e5dc/Frequently_used_code/Virtual_products.ipynb

**Comment by robbibt** [comment]
Now available on the Sandbox
