### ISSUE TITLE
Upgrade to Python 3.10

### ISSUE THREAD

**Issue by omad** [GeoscienceAustralia/dea-sandbox#266]
Python 3.8 is getting old, and some libraries are dropping support for it.

I've built binary wheels of hdstats (In packages.dea.ga.gov.au) for Python 3.9, 3.10 and 3.11, which AFAIK was the hold up for upgrading our version of Python.

Is there anything special required to try out a build with Python 3.10?

**Comment by emmaai** [comment]
> Is there anything special required to try out a build with Python 3.10?
- FC
- otps (tide model)

Theoretically anything with cython/c/fortran code. These two are what I'm aware of.

**Comment by omad** [comment]
I've got a Python 3.10 conda environment running locally with those, they must have installed safely from source.

But I haven't been trying in docker, so that could be a problem...
