### ISSUE TITLE
%matplotlib widget not working

### ISSUE THREAD

**Issue by CEKrause** [GeoscienceAustralia/dea-sandbox#47]
In the Sandbox, the magic `%matplotlib widget` does not currently work. 

When I use this widget then try to plot, I get a message that says `Loading widget...` but nothing actually draws.

I am using the developer instance of the Sandbox (with the larger memory).

**Comment by Kirill888** [comment]
can confirm, broken in old and new images

**Comment by Kirill888** [comment]
frixed by #61
