### ISSUE TITLE
Additional figure displayed from ipywidget

### ISSUE THREAD

**Issue by caitlinadams** [GeoscienceAustralia/dea-sandbox#53]
I'm working on transitioning the [Crop_health.ipynb](https://github.com/GeoscienceAustralia/dea-notebooks/blob/develop/Real_world_examples/Crop_health.ipynb) notebook from DE Australia to DE Africa. I'm currently experiencing an issue where an empty figure is displayed below the widget when the code is run in the DE Africa sandbox (active work on [crophealth branch](https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/blob/crophealth/Real_world_examples/Crop_health.ipynb)). The code is working fine (no empty figure) in the DE Australia sandbox, so I think it's likely a difference in the environment?

![Screen Shot 2020-03-30 at 3 03 45 pm](https://user-images.githubusercontent.com/25995927/77965960-defbfc00-732d-11ea-84cd-e8f47e728bc0.png)

**Comment by caitlinadams** [comment]
No longer occuring, thanks!

**Comment by alexgleith** [comment]
I didn't fix it yet... curiouser and curiouser.
