### ISSUE TITLE
groups: cannot find name for group ID 40000

### ISSUE THREAD

**Issue by tom-butler** [GeoscienceAustralia/dea-sandbox#57]
After moving OTPS data to a shared EFS disk, users will see the following message when opening a terminal session. 

This is due to how the EFS-provisioner works, to hide this error we should create a group with id 4000 as part of the docker image creation process.

**Comment by alexgleith** [comment]
We just need to create the group?

**Comment by Kirill888** [comment]
Is 100% definitely always `40000`? I suggest group named `data` or `efs` with gid=40000 and add default user to that group. But I already had the issue of groups of the user in your normal docker run not match things when running in deployment. So I'm not 100% certain that k8s is not fiddling with `/etc/{shadow,groups}` .

**Comment by tom-butler** [comment]
It's definitely 40000 for all of our sandbox environments

**Comment by benjimin** [comment]
Just appending the line `other:x:40000:` to `/etc/group` (inside the container) should prevent this name-lookup failure.

I'm not exactly sure why the sandbox user is a member of a group with that gid in the first place, or for that matter why it is also a member of the _root_ group (in addition to the _users_ group). Presumably corresponds to a group created on the host OS (perhaps a "docker" group?) and somewhere the config neglected to renounce membership of those groups for the user's process?

Or perhaps it relates to EFS/glusterfs, which are often configured with `gidMin: "40000"` (the gid that gets assigned when a new storage volume is created), then necessitating efforts (related to #120 ) from jupyterhub to ensure that the ownership and/or privileges is changed back (for `jovyan:users`) [maybe](https://zero-to-jupyterhub.readthedocs.io/en/0.11.1/kubernetes/amazon/efs_storage.html)..
