### ISSUE TITLE
dask dashboard and jupyter-server-proxy=1.3.0 required

### ISSUE THREAD

**Issue by woodcockr** [GeoscienceAustralia/dea-sandbox#64]
Hi Folks,

This isn't my repo but I thought you might like to know that using a similar version setup to the dea-sandbox jupyter's dask dashboard and dask stopped talking to each other, so you now longer see Dask progress etc. Turns out there is a patch for jupyter-server-proxy which will need to be upgraded to 1.3.0. dea-sandbox as I write this is pinned at 1.1.0.

**Comment by caitlinadams** [comment]
I believe this is tied to the same issue as https://github.com/GeoscienceAustralia/dea-sandbox/issues/58

@tom-butler -- is it possible to have the jupyter-server-proxy upgraded as per @woodcockr's suggestion?

**Comment by woodcockr** [comment]
I just looked at #58, it looks familiar.
1.3.0 dropped straight in, no other changes.
