### ISSUE TITLE
Change Jupyterlab browser tab name

### ISSUE THREAD

**Issue by pindge** [GeoscienceAustralia/dea-sandbox#65]
In the JupyterLab area the browser tab name has been changed from `JupyterHub` to the corresponding sandbox environment
 
![image](https://user-images.githubusercontent.com/24644475/79181593-0c799700-7e50-11ea-9aa4-23b44f669efd.png)

Once user enters `JupyterLab` (Single user sandbox) the name displays `JupyterLab`
![image](https://user-images.githubusercontent.com/24644475/79181551-f10e8c00-7e4f-11ea-9824-3c7a55ef55e7.png)

According to https://github.com/jupyterlab/jupyterlab/issues/4422, this theming can be done with 
`jupyter lab build --name='MyJupyterLab'` in Docker build

**Comment by Kirill888** [comment]
This looks like a deployment concern and should go into deployment repo, currently we have this strange situation where this repo is primarily about building sandbox docker image but also includes some deployment scripts and configs like these ones:

https://github.com/GeoscienceAustralia/dea-sandbox/blob/master/docker/sync_repo
https://github.com/GeoscienceAustralia/dea-sandbox/blob/master/docker/jupyter_notebook_config.py

I think these should be moved out into the deployment repo as they have little to do with the docker image and everything to do with deployment. I guess this issue can be resolved by adding some config into the second link above, but I don't believe this needs to be happening in this repo.

**Comment by tom-butler** [comment]
It depends on a case-by-case basis where we put the commands / scripts etc. 

Running `jupyter lab build` on startup for every user would be a pretty poor solution, as it would increase the user login time by minutes. 

Making (yet another) github repo to take this image and add 'deployment concerns' is also a poor solution as there are already too many repositories in this build chain. This is intentionally a DEA specific repository in the GA organisation, if it was a generic Open Data Cube repo I'd agree, but it isn't. This repo creates a docker image that exists to be deployed in the DEA sandboxes. 

Where possible we can move chunks of this into the deployment config repo (we've already moved jupyter_notebook_config.py) - but it depends on the impacts of the change. If it's a small config file, sure it can be in that repo. If it's a change that needs to be included in docker build (like this change) it absolutely should be in this repo.

**Comment by pindge** [comment]
I have found a light-weight alternative.
under `/env/share/jupyter/lab/static` there is a file `index.html`
We can change everything here, including tab name and favicon
```
  <title>DEA DEV Sandbox</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {# Copy so we do not modify the page_config with updates. #}
{% set page_config_full = page_config.copy() %}

{# Set a dummy variable - we just want the side effect of the update. #}
{% set _ = page_config_full.update(baseUrl=base_url, wsUrl=ws_url) %}

  <script id="jupyter-config-data" type="application/json">
    {{ page_config_full | tojson }}
  </script>

  {% block favicon %}
  <link rel="icon" type="image/x-icon" href="{{ base_url | escape }}static/base/images/favicon.ico" class="idle favicon">
  <link rel="" type="image/x-icon" href="{{ base_url | escape }}static/base/images/favicon-busy-1.ico" class="busy favicon">
  {% endblock %}
```

![image](https://user-images.githubusercontent.com/24644475/79184543-c9bbbd00-7e57-11ea-9fcb-0910e1cf4554.png)

**Comment by Kirill888** [comment]
Ok, I didn't read this right, I have missed that this is a build-time concern and not a run-time concern. In this case having an ARG for the title would be acceptable in the Docker with DEA specific default.

Coming back to deployment vs building concerns split, your comment @tom-butler demonstrates exactly the problem I have with the current situation, if jupyter config file has already been moved, why is it still here? Somebody in the future will be editing it here and spend many hours debugging why it has no impact on deployment. Run-time concerns that are deployment specific should not be in this repo/docker image, unless you want to bring all the deployment files here as well.

This specific issue requires "build-time" fix, so that does belong here. Unless there is a way to turn this from build-time to run-time concern somehow.

**Comment by Kirill888** [comment]
done by #68

**Comment by WilliamJudge94** [comment]
You can find the jupyterlab path by typing `jupyter lab path` into a terminal. The Application directory path shows you where the correct files are stored. Inside that Application directory folder you can find the /static/index.html file to edit. 

Edit `<title>Jupyter Lab</title>` section inside the index.html file.

**Comment by euanmacinnes** [comment]
This was really useful. In the dockerized version, it's a simple "sed" command to replace this dynamically when each user's hub server starts.

...

Except it now no longer works properly in JupyterLab 3.0 as it now dynamically updates the tab, so the text gets mangled.
