### ISSUE TITLE
Missing JupyterLab icons in DEA Sandbox

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/dea-sandbox#66]
When logging in to the DEA Sandbox, some JupyterLab icons appear missing e.g. areas highlighted below:

![image](https://user-images.githubusercontent.com/17680388/79704194-9794da00-82f3-11ea-8c0e-6ba2d0d9fcbe.png)

This makes it difficult to work out what icons are what without hovering over them. Is there a solution for this issue?

I'm currently using the stable dev environment.

**Comment by pindge** [comment]
We need to see browser error logs to understand the issue. In chrome it is F12 to bring up DevTools - under `Console` tab

**Comment by tom-butler** [comment]
I've had it happen to me before, issue occurs when you have network issues whilst connecting to sandbox causing the missing images to be stored in your browser cache.

Clear your cache and it should clear up

**Comment by robbibt** [comment]
Clearing my cache seems to have fixed this issue 👍
