### ISSUE TITLE
Install pysheds library in sandbox environment

### ISSUE THREAD

**Issue by CEKrause** [GeoscienceAustralia/dea-sandbox#69]
For our work on wetlands depth analysis, we have been using a package called 'pysheds'. https://github.com/mdbartos/pysheds

It would be really great if we could include this in the sandbox environment. I have been installing it into my own user environment and haven't found any issues with it interfering with other packages. 
If it matters, this is how I have been using it:
```
$ git clone https://github.com/mdbartos/pysheds.git
$ cd pysheds
$ pip install .
```

**Comment by Kirill888** [comment]
installed in the latest image
