### ISSUE TITLE
lost+found folder on DE Africa Sandbox

### ISSUE THREAD

**Issue by caitlinadams** [GeoscienceAustralia/dea-sandbox#72]
I've noticed an empty folder called `lost+found` on my instance of the DE Africa Sandbox (both on my regularly used user, and a clean test user I made a while ago). It's not part of the DE Africa Notebooks repo, so I'm not sure where it's coming from. Is someone able to confirm whether this always gets created when you make a new user? If it's not being used for anything, can it be safely removed?

We'll be recording demonstrations in the next week, and I want to make sure I can tidy up anything that looks out of place. Thanks!

![Screen Shot 2020-04-23 at 11 22 43 am](https://user-images.githubusercontent.com/25995927/80049063-45eb8a00-8555-11ea-8fe8-50ee95629452.png)

**Comment by whatnick** [comment]
Since sandboxes get frequently terminated the Linux filesystem keeps copies of files in transit here. It is part of Linux and we may have to perform file-system tweaks on the container/pvc to hide them.

https://www.howtogeek.com/282374/what-is-the-lostfound-folder-on-linux-and-macos/

**Comment by Kirill888** [comment]
I think it should be safe to delete this folder if it's empty during startup. Something like this will do the trick:
```bash
rmdir "${HOME}/lost+found" || true
```

Above will keep this folder around if it DOES contain data, user can then have a look inside and see if anything of value is there.

**Comment by whatnick** [comment]
Recently it bothered me so I did a 
```
mv "${HOME}/lost+found" "${HOME}/.lost+found"
```
I will put that in the startup script somewhere.
