### ISSUE TITLE
Bokeh embedded server not working

### ISSUE THREAD

**Issue by emmaai** [GeoscienceAustralia/dea-sandbox#78]
Test script
[https://github.com/GeoscienceAustralia/wit_tooling/blob/master/examples/test_bokeh_server.ipynb](https://github.com/GeoscienceAustralia/wit_tooling/blob/master/examples/test_bokeh_server.ipynb)

Supposed behavior: Plot at the end of `show`

Actual behavior: Nothing but the printed log. Open browser debug console can see jscript error messages.

```
Source map error: request failed with status 403
Resource URL: https://cdn.pydata.org/bokeh/release/bokeh-1.4.0.min.js
Source Map URL: bokeh.min.js.map
```
While the url [https://cdn.pydata.org/bokeh/release/bokeh-1.4.0.min.js]( https://cdn.pydata.org/bokeh/release/bokeh-1.4.0.min.js) is very not forbidden.

**Comment by alexgleith** [comment]
That says that the source map is `403` forbidden, which is not a fatal issue. That's the JavaScript source map, I think, used to de-minify the source for debugging.

**Comment by NikitaGandhi** [comment]
This is WAF related issue which is blocking `autoload.js`.  Will fix rules to support this.

**Comment by Kirill888** [comment]
fixed by adjusting deployment WAF rules.
