### ISSUE TITLE
Conflicting Dependencies with jupyterlab/git@0.20.0

### ISSUE THREAD

**Issue by patrickmuston1** [GeoscienceAustralia/dea-sandbox#82]
Hi everyone,
I received the below error while installing a local image of the dea-sandbox. Requiring version jupyterlab-git==0.10.1 in the requirements-jupyter.txt file on my local version fixed the issue. Should I update the dependencies, or require a specific version number for jupyterlab/git as I have done? Not sure what is best practice/what the plans for these dependencies are.

"@jupyterlab/git@0.20.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension        Package
>=1.2.2 <1.3.0          >=2.0.0 <3.0.0   @jupyterlab/application
>=1.2.2 <1.3.0          >=2.0.0 <3.0.0   @jupyterlab/apputils
>=1.2.3 <1.3.0          >=2.0.0 <3.0.0   @jupyterlab/console
>=3.2.0 <3.3.0          >=4.0.0 <5.0.0   @jupyterlab/coreutils
>=1.2.2 <1.3.0          >=2.0.0 <3.0.0   @jupyterlab/filebrowser
>=4.2.0 <4.3.0          >=5.0.0 <6.0.0   @jupyterlab/services
>=1.2.2 <1.3.0          >=2.0.0 <3.0.0   @jupyterlab/terminal
>=16.8.4 <16.9.0        >=16.9.0 <16.10.0react
>=16.8.4 <16.9.0        >=16.9.0 <16.10.0react-dom

**Comment by alexgleith** [comment]
If you can create a PR that would be great!

The dependency tree is pretty hard...

**Comment by Kirill888** [comment]
@patrickmuston1 you are quite right, looks like we are not pinning that lib in python

https://github.com/GeoscienceAustralia/dea-sandbox/blob/57829e0bab3aeda958d53b5ffe239ba6eec4592c/docker/requirements-jupyter.txt#L14

but pin `jupyterlab` and everything else. We should really bump everything up to latest versions and then add pin for `jupyterlab-git==0.20.0`. Last build of this repo did have `jupyterlab-git==0.10.0` installed which worked fine.

**Comment by Kirill888** [comment]
After updating various jupyter libs and pinning them afterwards this problem not longer happens
