### ISSUE TITLE
Typo in Digital Earth Africa Beginners MD file

### ISSUE THREAD

**Issue by kitmacleod** [GeoscienceAustralia/dea-sandbox#89]
A great resource. A typo in the MD file 'Digital Erath Africa'.

**Comment by alexgleith** [comment]
Which file has the typo?

**Comment by Kirill888** [comment]
@alexgleith I think it's this one: 
https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/blob/master/Beginners_guide/README.md

**Comment by Kirill888** [comment]
@kitmacleod thanks for reporting, will be fixed soon in the notebooks repo

https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/pull/117
